"""empty message

Revision ID: 50f937245e73
Revises: None
Create Date: 2015-10-20 23:25:14.292842

"""

# revision identifiers, used by Alembic.
revision = '50f937245e73'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Credentials',
    sa.Column('session_id', sa.String(), nullable=False),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('password', sa.String(), nullable=True),
    sa.Column('key', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('session_id'),
    sa.UniqueConstraint('session_id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Credentials')
    ### end Alembic commands ###
