"""empty message

Revision ID: 5a70a96dd5ec
Revises: None
Create Date: 2015-10-28 13:32:17.241989

"""

# revision identifiers, used by Alembic.
revision = '5a70a96dd5ec'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'credentials', ['session_id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'credentials', type_='unique')
    ### end Alembic commands ###
