"""empty message

Revision ID: 622cd781398
Revises: 50f937245e73
Create Date: 2015-10-22 12:04:39.838388

"""

# revision identifiers, used by Alembic.
revision = '622cd781398'
down_revision = '50f937245e73'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Credentials', sa.Column('last_used_on', sa.DateTime(), nullable=True))
    op.add_column('Credentials', sa.Column('registered_on', sa.DateTime(), nullable=True))
    op.create_unique_constraint(None, 'Credentials', ['session_id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'Credentials', type_='unique')
    op.drop_column('Credentials', 'registered_on')
    op.drop_column('Credentials', 'last_used_on')
    ### end Alembic commands ###
